//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace FilteringSystem.filter {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.benilde.edu.ph/pp/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetEmpOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserTypeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::FilteringSystem.Properties.Settings.Default.FilteringSystem_filter_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetEmpCompletedEventHandler GetEmpCompleted;
        
        /// <remarks/>
        public event GetBatchCompletedEventHandler GetBatchCompleted;
        
        /// <remarks/>
        public event GetStudCompletedEventHandler GetStudCompleted;
        
        /// <remarks/>
        public event GetUserTypeCompletedEventHandler GetUserTypeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.benilde.edu.ph/pp/GetEmp", RequestNamespace="http://www.benilde.edu.ph/pp/", ResponseNamespace="http://www.benilde.edu.ph/pp/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpEntity[] GetEmp(string key) {
            object[] results = this.Invoke("GetEmp", new object[] {
                        key});
            return ((EmpEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpAsync(string key) {
            this.GetEmpAsync(key, null);
        }
        
        /// <remarks/>
        public void GetEmpAsync(string key, object userState) {
            if ((this.GetEmpOperationCompleted == null)) {
                this.GetEmpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpOperationCompleted);
            }
            this.InvokeAsync("GetEmp", new object[] {
                        key}, this.GetEmpOperationCompleted, userState);
        }
        
        private void OnGetEmpOperationCompleted(object arg) {
            if ((this.GetEmpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpCompleted(this, new GetEmpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.benilde.edu.ph/pp/GetBatch", RequestNamespace="http://www.benilde.edu.ph/pp/", ResponseNamespace="http://www.benilde.edu.ph/pp/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BatchEntity[] GetBatch(string key, string batch) {
            object[] results = this.Invoke("GetBatch", new object[] {
                        key,
                        batch});
            return ((BatchEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBatchAsync(string key, string batch) {
            this.GetBatchAsync(key, batch, null);
        }
        
        /// <remarks/>
        public void GetBatchAsync(string key, string batch, object userState) {
            if ((this.GetBatchOperationCompleted == null)) {
                this.GetBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBatchOperationCompleted);
            }
            this.InvokeAsync("GetBatch", new object[] {
                        key,
                        batch}, this.GetBatchOperationCompleted, userState);
        }
        
        private void OnGetBatchOperationCompleted(object arg) {
            if ((this.GetBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBatchCompleted(this, new GetBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.benilde.edu.ph/pp/GetStud", RequestNamespace="http://www.benilde.edu.ph/pp/", ResponseNamespace="http://www.benilde.edu.ph/pp/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudEntity[] GetStud(string key, string sy, string term) {
            object[] results = this.Invoke("GetStud", new object[] {
                        key,
                        sy,
                        term});
            return ((StudEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStudAsync(string key, string sy, string term) {
            this.GetStudAsync(key, sy, term, null);
        }
        
        /// <remarks/>
        public void GetStudAsync(string key, string sy, string term, object userState) {
            if ((this.GetStudOperationCompleted == null)) {
                this.GetStudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudOperationCompleted);
            }
            this.InvokeAsync("GetStud", new object[] {
                        key,
                        sy,
                        term}, this.GetStudOperationCompleted, userState);
        }
        
        private void OnGetStudOperationCompleted(object arg) {
            if ((this.GetStudCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudCompleted(this, new GetStudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.benilde.edu.ph/pp/GetUserType", RequestNamespace="http://www.benilde.edu.ph/pp/", ResponseNamespace="http://www.benilde.edu.ph/pp/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserTypeEntity[] GetUserType(string key, string user, string pass) {
            object[] results = this.Invoke("GetUserType", new object[] {
                        key,
                        user,
                        pass});
            return ((UserTypeEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserTypeAsync(string key, string user, string pass) {
            this.GetUserTypeAsync(key, user, pass, null);
        }
        
        /// <remarks/>
        public void GetUserTypeAsync(string key, string user, string pass, object userState) {
            if ((this.GetUserTypeOperationCompleted == null)) {
                this.GetUserTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserTypeOperationCompleted);
            }
            this.InvokeAsync("GetUserType", new object[] {
                        key,
                        user,
                        pass}, this.GetUserTypeOperationCompleted, userState);
        }
        
        private void OnGetUserTypeOperationCompleted(object arg) {
            if ((this.GetUserTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserTypeCompleted(this, new GetUserTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.benilde.edu.ph/pp/")]
    public partial class EmpEntity {
        
        private string nameField;
        
        private string lnameField;
        
        private string fnameField;
        
        private string mnameField;
        
        private string idnoField;
        
        private string locationField;
        
        private string pdeptcodeField;
        
        private string cdeptcodeField;
        
        private string deptcodeField;
        
        private string statusField;
        
        private string typeField;
        
        private string infonetField;
        
        private string emailField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Lname {
            get {
                return this.lnameField;
            }
            set {
                this.lnameField = value;
            }
        }
        
        /// <remarks/>
        public string Fname {
            get {
                return this.fnameField;
            }
            set {
                this.fnameField = value;
            }
        }
        
        /// <remarks/>
        public string Mname {
            get {
                return this.mnameField;
            }
            set {
                this.mnameField = value;
            }
        }
        
        /// <remarks/>
        public string Idno {
            get {
                return this.idnoField;
            }
            set {
                this.idnoField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string Pdeptcode {
            get {
                return this.pdeptcodeField;
            }
            set {
                this.pdeptcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Cdeptcode {
            get {
                return this.cdeptcodeField;
            }
            set {
                this.cdeptcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Deptcode {
            get {
                return this.deptcodeField;
            }
            set {
                this.deptcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Infonet {
            get {
                return this.infonetField;
            }
            set {
                this.infonetField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.benilde.edu.ph/pp/")]
    public partial class UserTypeEntity {
        
        private string typeField;
        
        private string groupField;
        
        private string subGroupField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public string SubGroup {
            get {
                return this.subGroupField;
            }
            set {
                this.subGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.benilde.edu.ph/pp/")]
    public partial class StudEntity {
        
        private string idnoField;
        
        private string syField;
        
        private string termField;
        
        private string degreeField;
        
        private string schoolField;
        
        /// <remarks/>
        public string Idno {
            get {
                return this.idnoField;
            }
            set {
                this.idnoField = value;
            }
        }
        
        /// <remarks/>
        public string Sy {
            get {
                return this.syField;
            }
            set {
                this.syField = value;
            }
        }
        
        /// <remarks/>
        public string Term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
            }
        }
        
        /// <remarks/>
        public string Degree {
            get {
                return this.degreeField;
            }
            set {
                this.degreeField = value;
            }
        }
        
        /// <remarks/>
        public string School {
            get {
                return this.schoolField;
            }
            set {
                this.schoolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.benilde.edu.ph/pp/")]
    public partial class BatchEntity {
        
        private string batchField;
        
        private string idnoField;
        
        private string fnameField;
        
        private string lnameField;
        
        private string mnameField;
        
        private string citizenshipField;
        
        private string genderField;
        
        private string birthdateField;
        
        private string religionField;
        
        private string studtypeinField;
        
        private string syinField;
        
        private string terminField;
        
        private string studtypeoutField;
        
        private string syoutField;
        
        private string termoutField;
        
        private string nostreetField;
        
        private string cityProvField;
        
        private string regionField;
        
        private string zipcodeField;
        
        private string telnoField;
        
        private string degreeField;
        
        private string schoolField;
        
        /// <remarks/>
        public string Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
            }
        }
        
        /// <remarks/>
        public string Idno {
            get {
                return this.idnoField;
            }
            set {
                this.idnoField = value;
            }
        }
        
        /// <remarks/>
        public string Fname {
            get {
                return this.fnameField;
            }
            set {
                this.fnameField = value;
            }
        }
        
        /// <remarks/>
        public string Lname {
            get {
                return this.lnameField;
            }
            set {
                this.lnameField = value;
            }
        }
        
        /// <remarks/>
        public string Mname {
            get {
                return this.mnameField;
            }
            set {
                this.mnameField = value;
            }
        }
        
        /// <remarks/>
        public string Citizenship {
            get {
                return this.citizenshipField;
            }
            set {
                this.citizenshipField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string Birthdate {
            get {
                return this.birthdateField;
            }
            set {
                this.birthdateField = value;
            }
        }
        
        /// <remarks/>
        public string Religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
            }
        }
        
        /// <remarks/>
        public string Studtypein {
            get {
                return this.studtypeinField;
            }
            set {
                this.studtypeinField = value;
            }
        }
        
        /// <remarks/>
        public string Syin {
            get {
                return this.syinField;
            }
            set {
                this.syinField = value;
            }
        }
        
        /// <remarks/>
        public string Termin {
            get {
                return this.terminField;
            }
            set {
                this.terminField = value;
            }
        }
        
        /// <remarks/>
        public string Studtypeout {
            get {
                return this.studtypeoutField;
            }
            set {
                this.studtypeoutField = value;
            }
        }
        
        /// <remarks/>
        public string Syout {
            get {
                return this.syoutField;
            }
            set {
                this.syoutField = value;
            }
        }
        
        /// <remarks/>
        public string Termout {
            get {
                return this.termoutField;
            }
            set {
                this.termoutField = value;
            }
        }
        
        /// <remarks/>
        public string Nostreet {
            get {
                return this.nostreetField;
            }
            set {
                this.nostreetField = value;
            }
        }
        
        /// <remarks/>
        public string CityProv {
            get {
                return this.cityProvField;
            }
            set {
                this.cityProvField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string Zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Telno {
            get {
                return this.telnoField;
            }
            set {
                this.telnoField = value;
            }
        }
        
        /// <remarks/>
        public string Degree {
            get {
                return this.degreeField;
            }
            set {
                this.degreeField = value;
            }
        }
        
        /// <remarks/>
        public string School {
            get {
                return this.schoolField;
            }
            set {
                this.schoolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetEmpCompletedEventHandler(object sender, GetEmpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmpEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmpEntity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetBatchCompletedEventHandler(object sender, GetBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BatchEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BatchEntity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetStudCompletedEventHandler(object sender, GetStudCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudEntity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetUserTypeCompletedEventHandler(object sender, GetUserTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserTypeEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserTypeEntity[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591